export const SET_USER = 'SET_USER'
export const SET_AUTH_LOADING_SATUS = 'SET_AUTH_LOADING_SATUS'
export const SET_AUTH_AUTHENTICATED = 'SET_AUTH_AUTHENTICATED'
export const SET_AUTH_CLIENT = 'SET_AUTH_CLIENT'
